name: testing python implementation

on:
  pull_request:
    branches:
      - main
    paths-ignore: ['README.md', 'LICENSE', '.gitignore', 'spec/**']
jobs:
  runtests-python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: run tests
      run: |
        make bootstrap PLANCK_IMPL=python
        make test
