name: testing c implementation

on:
  pull_request:
    branches:
      - main
    paths-ignore: ['README.md', 'LICENSE', '.gitignore', 'spec/**']
jobs:
  runtests-c:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: run tests
      run: |
        make bootstrap PLANCK_IMPL=c
        make test
        make test-vm VM_IMPL=c
